[providers]
python = "3.11"
node = "20"

[build]
cmd = "cd frontend && npm install && npm run build && cd .. && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"

[start]
cmd = "gunicorn core.wsgi --bind 0.0.0.0:$PORT --log-file -"
